/**
 * videoapi
 * The video APIs help you convert, encode, and transcode videos.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveVideoApiClient);
  }
}(this, function(expect, CloudmersiveVideoApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveVideoApiClient.MediaInformation();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MediaInformation', function() {
    it('should create an instance of MediaInformation', function() {
      // uncomment below and update the code to test MediaInformation
      //var instance = new CloudmersiveVideoApiClient.MediaInformation();
      //expect(instance).to.be.a(CloudmersiveVideoApiClient.MediaInformation);
    });

    it('should have the property successful (base name: "Successful")', function() {
      // uncomment below and update the code to test the property successful
      //var instance = new CloudmersiveVideoApiClient.MediaInformation();
      //expect(instance).to.be();
    });

    it('should have the property fileFormat (base name: "FileFormat")', function() {
      // uncomment below and update the code to test the property fileFormat
      //var instance = new CloudmersiveVideoApiClient.MediaInformation();
      //expect(instance).to.be();
    });

    it('should have the property fileFormatFull (base name: "FileFormatFull")', function() {
      // uncomment below and update the code to test the property fileFormatFull
      //var instance = new CloudmersiveVideoApiClient.MediaInformation();
      //expect(instance).to.be();
    });

    it('should have the property validFileFormats (base name: "ValidFileFormats")', function() {
      // uncomment below and update the code to test the property validFileFormats
      //var instance = new CloudmersiveVideoApiClient.MediaInformation();
      //expect(instance).to.be();
    });

    it('should have the property width (base name: "Width")', function() {
      // uncomment below and update the code to test the property width
      //var instance = new CloudmersiveVideoApiClient.MediaInformation();
      //expect(instance).to.be();
    });

    it('should have the property height (base name: "Height")', function() {
      // uncomment below and update the code to test the property height
      //var instance = new CloudmersiveVideoApiClient.MediaInformation();
      //expect(instance).to.be();
    });

    it('should have the property size (base name: "Size")', function() {
      // uncomment below and update the code to test the property size
      //var instance = new CloudmersiveVideoApiClient.MediaInformation();
      //expect(instance).to.be();
    });

    it('should have the property bitRate (base name: "BitRate")', function() {
      // uncomment below and update the code to test the property bitRate
      //var instance = new CloudmersiveVideoApiClient.MediaInformation();
      //expect(instance).to.be();
    });

    it('should have the property duration (base name: "Duration")', function() {
      // uncomment below and update the code to test the property duration
      //var instance = new CloudmersiveVideoApiClient.MediaInformation();
      //expect(instance).to.be();
    });

    it('should have the property startTime (base name: "StartTime")', function() {
      // uncomment below and update the code to test the property startTime
      //var instance = new CloudmersiveVideoApiClient.MediaInformation();
      //expect(instance).to.be();
    });

  });

}));
