/**
 * videoapi
 * The video APIs help you convert, encode, and transcode videos.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveVideoApiClient);
  }
}(this, function(expect, CloudmersiveVideoApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveVideoApiClient.StillFrame();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('StillFrame', function() {
    it('should create an instance of StillFrame', function() {
      // uncomment below and update the code to test StillFrame
      //var instance = new CloudmersiveVideoApiClient.StillFrame();
      //expect(instance).to.be.a(CloudmersiveVideoApiClient.StillFrame);
    });

    it('should have the property frameNumber (base name: "FrameNumber")', function() {
      // uncomment below and update the code to test the property frameNumber
      //var instance = new CloudmersiveVideoApiClient.StillFrame();
      //expect(instance).to.be();
    });

    it('should have the property timeStamp (base name: "TimeStamp")', function() {
      // uncomment below and update the code to test the property timeStamp
      //var instance = new CloudmersiveVideoApiClient.StillFrame();
      //expect(instance).to.be();
    });

    it('should have the property content (base name: "Content")', function() {
      // uncomment below and update the code to test the property content
      //var instance = new CloudmersiveVideoApiClient.StillFrame();
      //expect(instance).to.be();
    });

  });

}));
