/**
 * videoapi
 * The video APIs help you convert, encode, and transcode videos.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveVideoApiClient);
  }
}(this, function(expect, CloudmersiveVideoApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveVideoApiClient.VideoApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VideoApi', function() {
    describe('videoConvertToGif', function() {
      it('should call videoConvertToGif successfully', function(done) {
        //uncomment below and update the code to test videoConvertToGif
        //instance.videoConvertToGif(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('videoConvertToMov', function() {
      it('should call videoConvertToMov successfully', function(done) {
        //uncomment below and update the code to test videoConvertToMov
        //instance.videoConvertToMov(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('videoConvertToMp4', function() {
      it('should call videoConvertToMp4 successfully', function(done) {
        //uncomment below and update the code to test videoConvertToMp4
        //instance.videoConvertToMp4(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('videoConvertToWebm', function() {
      it('should call videoConvertToWebm successfully', function(done) {
        //uncomment below and update the code to test videoConvertToWebm
        //instance.videoConvertToWebm(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('videoGetInfo', function() {
      it('should call videoGetInfo successfully', function(done) {
        //uncomment below and update the code to test videoGetInfo
        //instance.videoGetInfo(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
