/**
 * videoapi
 * The video APIs help you convert, encode, and transcode videos.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveVideoApiClient) {
      root.CloudmersiveVideoApiClient = {};
    }
    root.CloudmersiveVideoApiClient.NsfwScannedFrame = factory(root.CloudmersiveVideoApiClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The NsfwScannedFrame model module.
   * @module model/NsfwScannedFrame
   * @version 2.0.2
   */

  /**
   * Constructs a new <code>NsfwScannedFrame</code>.
   * An individual frame scanned for NSFW content
   * @alias module:model/NsfwScannedFrame
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>NsfwScannedFrame</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NsfwScannedFrame} obj Optional instance to populate.
   * @return {module:model/NsfwScannedFrame} The populated <code>NsfwScannedFrame</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('FrameNumber')) {
        obj['FrameNumber'] = ApiClient.convertToType(data['FrameNumber'], 'Number');
      }
      if (data.hasOwnProperty('TimeStamp')) {
        obj['TimeStamp'] = ApiClient.convertToType(data['TimeStamp'], 'String');
      }
      if (data.hasOwnProperty('Content')) {
        obj['Content'] = ApiClient.convertToType(data['Content'], 'Blob');
      }
      if (data.hasOwnProperty('ClassificationResult')) {
        obj['ClassificationResult'] = ApiClient.convertToType(data['ClassificationResult'], 'String');
      }
      if (data.hasOwnProperty('Score')) {
        obj['Score'] = ApiClient.convertToType(data['Score'], 'Number');
      }
    }
    return obj;
  }

  /**
   * The number of the current frame
   * @member {Number} FrameNumber
   */
  exports.prototype['FrameNumber'] = undefined;
  /**
   * The playback time of the current frame
   * @member {String} TimeStamp
   */
  exports.prototype['TimeStamp'] = undefined;
  /**
   * The still frame in PNG format as a byte array
   * @member {Blob} Content
   */
  exports.prototype['Content'] = undefined;
  /**
   * The NSFW classification of the still frame
   * @member {String} ClassificationResult
   */
  exports.prototype['ClassificationResult'] = undefined;
  /**
   * The NSFW score of the current frame
   * @member {Number} Score
   */
  exports.prototype['Score'] = undefined;



  return exports;
}));


