/**
 * videoapi
 * The video APIs help you convert, encode, and transcode videos.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/VideoFile'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./VideoFile'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveVideoApiClient) {
      root.CloudmersiveVideoApiClient = {};
    }
    root.CloudmersiveVideoApiClient.SplitVideoResult = factory(root.CloudmersiveVideoApiClient.ApiClient, root.CloudmersiveVideoApiClient.VideoFile);
  }
}(this, function(ApiClient, VideoFile) {
  'use strict';




  /**
   * The SplitVideoResult model module.
   * @module model/SplitVideoResult
   * @version 2.0.2
   */

  /**
   * Constructs a new <code>SplitVideoResult</code>.
   * The result of splitting a video
   * @alias module:model/SplitVideoResult
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>SplitVideoResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SplitVideoResult} obj Optional instance to populate.
   * @return {module:model/SplitVideoResult} The populated <code>SplitVideoResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Successful')) {
        obj['Successful'] = ApiClient.convertToType(data['Successful'], 'Boolean');
      }
      if (data.hasOwnProperty('Videos')) {
        obj['Videos'] = ApiClient.convertToType(data['Videos'], [VideoFile]);
      }
    }
    return obj;
  }

  /**
   * True if the operation was successful, false otherwise
   * @member {Boolean} Successful
   */
  exports.prototype['Successful'] = undefined;
  /**
   * Individual video files resulting from the split operation
   * @member {Array.<module:model/VideoFile>} Videos
   */
  exports.prototype['Videos'] = undefined;



  return exports;
}));


